# DON'T EDIT OR DELETE THIS FILE. IT USING LIKE AS STAMP FOR ANOTHER PROJECTS!!!
user: user # this user MUST have access for remote_root and subdirs
password: password
address: 192.168.1.20
port: 22
local_root: /home/test # may end in /, but not necessarily
remote_root: /home/test
ssh_private_key: false # if you using ssh private_key, use key path instead of 'false'
paths: # any full path would look like local_root/local_file or remote_root/remote_dir
  - local_dir/local_file remote_dir/remote_file # remote dir mast be created and DON'T use / in end of path
  - local_dir/ remote_dir/ # use end backslash for dirs
